[package]
name = "counter_program"
version = "0.1.0"
edition = "2021"

[dependencies]
anchor-lang = "0.30.1"  # match your Anchor version

[lib]
crate-type = ["cdylib", "lib"]
name = "counter_program"

[features]
no-entrypoint = []

